name: Check new release

on:
  pull_request: null
  push:
    branches:
    - main

jobs:
  build:
    name: Check new release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ghc: ["9.2.2"]

    steps:
    - uses: actions/checkout@v2
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/snapshot.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - uses: haskell/actions/setup@v1.2.7
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true

    - name: Run script
      run: stack --system-ghc --resolver snapshot.yaml script Check.hs snapshot.yaml
