name: Execute Sample

on:
  pull_request: null
  push:
    branches:
    - main

jobs:
  build:
    name: Execute each sample codes
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["9.2.1"]
    steps:
    - uses: actions/checkout@v2
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/snapshot.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - uses: haskell/actions/setup@v1.2.7
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true

    - name: Install dependencies
      run: stack --system-ghc build --only-dependencies
      working-directory: sample
